{
  "schema_version": "1.4.0",
  "id": "GHSA-8x94-hmjh-97hq",
  "modified": "2022-09-16T21:38:06Z",
  "published": "2022-08-11T14:49:12Z",
  "aliases": [
    "CVE-2022-36359"
  ],
  "summary": "Django vulnerable to Reflected File Download attack ",
  "details": "An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2"
            },
            {
              "fixed": "3.2.15"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.0"
            },
            {
              "fixed": "4.0.7"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2"
            },
            {
              "fixed": "3.2.15"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.0"
            },
            {
              "fixed": "4.0.7"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-36359"
    },
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/4.0/releases/security/"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-8x94-hmjh-97hq"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/django/django"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-245.yaml"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/g/django-announce/c/8cz--gvaJr4"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20220915-0008/"
    },
    {
      "type": "WEB",
      "url": "https://www.debian.org/security/2022/dsa-5254"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2022/aug/03/security-releases/"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2022/08/03/1"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-494"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2022-08-11T14:49:12Z",
    "nvd_published_at": "2022-08-03T14:15:00Z"
  }
}