{
  "schema_version": "1.4.0",
  "id": "GHSA-w24h-v9qh-8gxj",
  "modified": "2022-04-22T20:32:48Z",
  "published": "2022-04-13T00:00:33Z",
  "aliases": [
    "CVE-2022-28347"
  ],
  "summary": "SQL Injection in Django",
  "details": "A SQL injection issue was discovered in QuerySet.explain() in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. This occurs by passing a crafted dictionary (with dictionary expansion) as the **options argument, and placing the injection payload in an option name.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.explain"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "2.2"
            },
            {
              "fixed": "2.2.28"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.explain"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2"
            },
            {
              "fixed": "3.2.13"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.explain"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.0"
            },
            {
              "fixed": "4.0.4"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-28347"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"
    },
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/4.0/releases/security/"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-w24h-v9qh-8gxj"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/django/django"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/forum/#!forum/django-announce"
    },
    {
      "type": "WEB",
      "url": "https://www.debian.org/security/2022/dsa-5254"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2022/04/11/1"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-89"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2022-04-22T20:32:48Z",
    "nvd_published_at": "2022-04-12T05:15:00Z"
  }
}