{
  "schema_version": "1.4.0",
  "id": "GHSA-2gwj-7jmv-h26r",
  "modified": "2022-04-22T20:33:03Z",
  "published": "2022-04-13T00:00:33Z",
  "aliases": [
    "CVE-2022-28346"
  ],
  "summary": "SQL Injection in Django",
  "details": "An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.annotate",
          "django.db.models.QuerySet.aggregate",
          "django.db.models.QuerySet.extra"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "2.2"
            },
            {
              "fixed": "2.2.28"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.annotate",
          "django.db.models.QuerySet.aggregate",
          "django.db.models.QuerySet.extra"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2"
            },
            {
              "fixed": "3.2.13"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.db.models.QuerySet.annotate",
          "django.db.models.QuerySet.aggregate",
          "django.db.models.QuerySet.extra"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.0"
            },
            {
              "fixed": "4.0.4"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-28346"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"
    },
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/4.0/releases/security/"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-2gwj-7jmv-h26r"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/django/django"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/forum/#!forum/django-announce"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20220609-0002/"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2022/04/11/1"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-89"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2022-04-22T20:33:03Z",
    "nvd_published_at": "2022-04-12T05:15:00Z"
  }
}